eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9001/user/info
    client:
      id: client
      client-secret: client
      access-token-uri: http://localhost:9001/oauth/token
      grant-type: password
      scope: all